# 服务配置
server:
  port: 9011
  tomcat:
    uri-encoding: UTF-8
    # 加大tomcat最大连接数, 这里给400
    accept-count: 400
    max-connections: 400
    threads:
      max: 400

# spring配置
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
      # Custom=true 配置自定义CustomGatewayFilterFactory  ，Custom是CustomGatewayFilterFactory的前缀，gateway默认省略GatewayFilterFactory
      #- CustomGatewayFilterFactory
      routes:
      - id: system-web
        uri: lb://system-web
        predicates:
        - Path=/api/system-web/**
        filters:
#        - SwaggerHeaderFilter
        - StripPrefix=2
      - id: statistics
        uri: lb://statistics
        predicates:
        - Path=/api/statistics/**
        filters:
#        - SwaggerHeaderFilter
        - StripPrefix=2

# 调度中心配置
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:60011/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

referer:
  domain: 150.103.73.215