spring:
  profiles:
    active: dev
  application:
    name: statistics
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: UTF-8
