server:
  servlet:
    context-path: /
  port: 8086
  tomcat:
    uri-encoding: UTF-8
    accept-count: 500
    max-threads: 500
    max-connections: 500
spring:
  main:
    allow-bean-definition-overriding: true
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: oracle #设置默认数据源
      strict: true # 设置严格模式，默认false，不启动
      datasource:
        oracle:
          url: jdbc:oracle:thin:@150.100.16.127:1521/dsjzt
          username: dsjzt_com
          password: dsjzt_5$%DaT^
          driver-class-name: oracle.jdbc.OracleDriver
          initialSize: 5
          minIdle: 5
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    database: 0
    host: 150.100.16.127
    port: 6379
    password: '!123@password'
    timeout: 15000
    encode: UTF-8
    block-when-exhausted: true
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 1
        max-wait: 15000
fbs:
  shiro:
    noPassword: false
    enabled: true
    expireIn: 1800
    sessionTimeout: 1800000
    sessionTimeoutClean: 120000
    cookieTimeout: 2592000
    anonUrl: /css/**,/js/**,/fonts/**,/adminres/**,/img/**,/auth/**,/swagger**
    authcUrl: '/menu/**,/office/**,/role/**'
    loginUrl: /auth/login
    successUrl: /admin/index
    logoutUrl: /auth/logout
    unauthorizedUrl: /403
    sessionIdName: sf.session.id
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hcf.ssqb.provider.mz.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      field-strategy: not-empty
      column-underline: true
      logic-delete-value: Y
      logic-not-delete-value: N
    refresh: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:60011/eureka/
  instance:
    appname: ${spring.application.name}
    virtualHostName: ${spring.application.name}
    secureVirtualHostName: ${spring.application.name}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  okhttp:
    enabled: false
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    com.hcf.nszh.provider.mz.mapper: DEBUG

minio:
  url: http://150.100.16.127:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: maruko