spring:
  profiles:
    active: dev
  application:
    name: statistics
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  aop:
    auto: true
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: UTF-8
