# 服务配置
server:
  port: 60011
  tomcat:
    uri-encoding: UTF-8
    # 加大tomcat最大连接数, 这里给400
    accept-count: 500
    max-threads: 500
    max-connections: 500

# spring配置
spring:
  application:
    name: eureka-service
  security:
    user:
      name: admin
      password: 123456

# 调度中心配置
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    use-read-only-response-cache: false
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:${server.port}/eureka/
